# Project information
site_name: 'ISCC - Content Identifiers'
site_description: 'International Standard Content Code - Specification'
site_author: 'Titusz Pan'
site_url: 'http://iscc.codes'

# Repository
repo_name: 'iscc/iscc-specs'
repo_url: 'https://github.com/iscc/iscc-specs'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright © 2016-2020 The Authors
| <a href="https://iscc.foundation/privacy">Privacy Policy</a>
| <a href="https://iscc.foundation/cookies">Cookie Policy</a>
| <a href="https://iscc.foundation/imprint">Imprint</a>
| <a href="https://iscc.foundation/disclaimer">Disclaimer</a>'

# Documentation and Theme
theme:
    name: 'material'
    language: 'en'
    logo: 'images/logo-white.svg'
    favicon: 'images/favicon.png'
    palette:
        primary: 'blue'
        accent: 'pink'
    feature:
        tabs: false

extra_css:
  - 'stylesheets/custom.css'

nav:
    - Overview: 'index.md'
    - Features: 'features.md'
    - Concept: 'concept.md'
    - Specification: 'specification.md'
    - Resources: 'resources.md'
    - Versions:
          - Version 1.x: 'specification.md'
          - Version 1.0: 'https://github.com/iscc/iscc-specs/blob/version-1.0/docs/specification.md'
    - License: 'license.md'

# Options
extra:
    search:
        language: 'en'
    social:
        - type: 'home'
          link: 'https://iscc.codes'
        - type: 'github'
          link: 'https://github.com/iscc'
        - type: 'telegram'
          link: 'https://t.me/iscc_dev'


markdown_extensions:
    - markdown.extensions.abbr
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
        linenums: false
        guess_lang: false
    - markdown.extensions.attr_list
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: '#'
    - pymdownx.magiclink

plugins:
    - search
    - git-revision-date
    - redirects:
          redirect_maps:
              'implementations.md': 'resources.md'

